nohup: ignoring input
True
True
---Generating data: 11.83552598953247 seconds ---
=============   train input size: (5460, 13) | validation input size: (2332, 13) | test input size(2228, 13) ==============
============ Number of Fog Cases: 103 
============ Number of Fog Cases: 31 
============ Number of Fog Cases: 67 
Epoch 001: | Train Loss: 0.1092 | Val Loss: 0.1058 | Time(s): 954.192
Best model Saved! Val Loss: 0.1058
count: 0
Epoch 002: | Train Loss: 0.0548 | Val Loss: 0.0728 | Time(s): 964.245
Best model Saved! Val Loss: 0.0728
count: 0
Epoch 003: | Train Loss: 0.0452 | Val Loss: 0.0832 | Time(s): 986.342
Model is not saved! Current Val Loss: 0.0832
count: 1
Epoch 004: | Train Loss: 0.0422 | Val Loss: 0.0786 | Time(s): 973.550
Model is not saved! Current Val Loss: 0.0786
count: 2
Epoch 005: | Train Loss: 0.0391 | Val Loss: 0.0965 | Time(s): 996.671
Model is not saved! Current Val Loss: 0.0965
count: 3
Epoch 006: | Train Loss: 0.0456 | Val Loss: 0.1112 | Time(s): 979.419
Model is not saved! Current Val Loss: 0.1112
count: 4
Epoch 007: | Train Loss: 0.0325 | Val Loss: 0.0983 | Time(s): 971.103
Model is not saved! Current Val Loss: 0.0983
count: 5
Epoch 008: | Train Loss: 0.0298 | Val Loss: 0.1113 | Time(s): 984.862
Model is not saved! Current Val Loss: 0.1113
count: 6
Epoch 009: | Train Loss: 0.0305 | Val Loss: 0.1275 | Time(s): 962.730
Model is not saved! Current Val Loss: 0.1275
count: 7
Epoch 010: | Train Loss: 0.0232 | Val Loss: 0.1194 | Time(s): 982.289
Model is not saved! Current Val Loss: 0.1194
count: 8
Epoch 011: | Train Loss: 0.0207 | Val Loss: 0.1289 | Time(s): 985.265
Model is not saved! Current Val Loss: 0.1289
count: 9
Epoch 012: | Train Loss: 0.0229 | Val Loss: 0.1521 | Time(s): 970.775
Model is not saved! Current Val Loss: 0.1521
count: 10
Epoch: 12
Traceback (most recent call last):
  File "train.py", line 235, in <module>
    Exp_name              = 'EX001_1D_All'
  File "train.py", line 222, in train_1d
    train_output, valid_output, test_output = engine.eval_1d(parallel_net, data_loader_training, data_loader_validate, data_loader_testing, Exp_name = Exp_name,)
  File "/data1/fog/TransMAP/models/engine.py", line 247, in eval_1d
    train_evaluation_metrics = train_eval_obj.confusion_matrix_calc()
  File "/data1/fog/TransMAP/models/engine.py", line 93, in confusion_matrix_calc
    Hit, miss, FA, CR = confusion_matrix(self.ytrue, ypred_class).ravel()
  File "/home/hkamangir/anaconda3/envs/deep-learning/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 268, in confusion_matrix
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/home/hkamangir/anaconda3/envs/deep-learning/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 80, in _check_targets
    check_consistent_length(y_true, y_pred)
  File "/home/hkamangir/anaconda3/envs/deep-learning/lib/python3.7/site-packages/sklearn/utils/validation.py", line 212, in check_consistent_length
    " samples: %r" % [int(l) for l in lengths])
ValueError: Found input variables with inconsistent numbers of samples: [5460, 84]
